### ISSUE TITLE
FPV, FNV for Swin UNETR

### ISSUE THREAD

**Issue by ricklisz** [heiligerl/AutoPET_Challenge_Submission#1]
Hi, 

I was reading your paper on arXiv. For Swin UNETR, I wonder if you happened to record the FPV and FNV? Right now I am training it in MONAI, but I got some very high FPV and FNV. 

Thanks!

**Comment by heiligerl** [comment]
Hello,

Thanks for reaching out. I must admit that these numbers should have been included in the paper. But I'm afraid that I cannot help you in this regard since I don't have access to the logs of my experiments anymore.

**Comment by ricklisz** [comment]
Thanks for your response! Could I ask whether you compared the difference between training Swin UENTR on non healthy vs healthy patients? I was curious why the nnUNET didn't benefit from training on healthy patients.

**Comment by heiligerl** [comment]
Sorry for the very late reply. Swin UNETR didn't benefit from training on all patients, hence we abandoned this path.
